config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :attorneys
  get 'msword', to: 'pages#msword'
  root 'pages#home'
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attorney.rb
class Attorney < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/attorneys_controller.rb
class AttorneysController < ApplicationController
  before_action :set_attorney, only: %i[ show edit update destroy ]

  # GET /attorneys or /attorneys.json
  def index
    @attorneys = Attorney.all
  end

  # GET /attorneys/1 or /attorneys/1.json
  def show
  end

  # GET /attorneys/new
  def new
    @attorney = Attorney.new
  end

  # GET /attorneys/1/edit
  def edit
  end

  # POST /attorneys or /attorneys.json
  def create
    @attorney = Attorney.new(attorney_params)

    respond_to do |format|
      if @attorney.save
        format.html { redirect_to attorney_url(@attorney), notice: "Attorney was successfully created." }
        format.json { render :show, status: :created, location: @attorney }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attorney.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attorneys/1 or /attorneys/1.json
  def update
    respond_to do |format|
      if @attorney.update(attorney_params)
        format.html { redirect_to attorney_url(@attorney), notice: "Attorney was successfully updated." }
        format.json { render :show, status: :ok, location: @attorney }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attorney.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attorneys/1 or /attorneys/1.json
  def destroy
    @attorney.destroy!

    respond_to do |format|
      format.html { redirect_to attorneys_url, notice: "Attorney was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attorney
      @attorney = Attorney.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attorney_params
      params.require(:attorney).permit(:sbn, :status, :full_name, :firm_name, :address, :city, :state, :zip, :tel, :email, :old_firm_name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def msword
    puts
    puts "ms word was called from the controller."
    goto_disc_folder
    download
    puts "completed tasks . . . "
  end

  def goto_disc_folder
      Dir.chdir(Rails.root.join("FOLDER", "PLEADINGS"))
  end

  def download
    send_file "cover_sheet.docx", :disposition => 'attachment'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attorneys_helper.rb
module AttorneysHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/attorneys/_attorney.html.erb
<div id="<%= dom_id attorney %>">
  <p>
    <strong>Sbn:</strong>
    <%= attorney.sbn %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= attorney.status %>
  </p>

  <p>
    <strong>Full name:</strong>
    <%= attorney.full_name %>
  </p>

  <p>
    <strong>Firm name:</strong>
    <%= attorney.firm_name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= attorney.address %>
  </p>

  <p>
    <strong>City:</strong>
    <%= attorney.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= attorney.state %>
  </p>

  <p>
    <strong>Zip:</strong>
    <%= attorney.zip %>
  </p>

  <p>
    <strong>Tel:</strong>
    <%= attorney.tel %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= attorney.email %>
  </p>

  <p>
    <strong>Old firm name:</strong>
    <%= attorney.old_firm_name %>
  </p>

</div>

app/views/attorneys/_form.html.erb
<%= form_with(model: attorney) do |form| %>
  <% if attorney.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(attorney.errors.count, "error") %> prohibited this attorney from being saved:</h2>

      <ul>
        <% attorney.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :sbn, style: "display: block" %>
    <%= form.text_field :sbn %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :full_name, style: "display: block" %>
    <%= form.text_field :full_name %>
  </div>

  <div>
    <%= form.label :firm_name, style: "display: block" %>
    <%= form.text_field :firm_name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :zip, style: "display: block" %>
    <%= form.text_field :zip %>
  </div>

  <div>
    <%= form.label :tel, style: "display: block" %>
    <%= form.text_field :tel %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :old_firm_name, style: "display: block" %>
    <%= form.text_field :old_firm_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/attorneys/edit.html.erb
<h1>Editing attorney</h1>

<%= render "form", attorney: @attorney %>

<br>

<div>
  <%= link_to "Show this attorney", @attorney %> |
  <%= link_to "Back to attorneys", attorneys_path %>
</div>

app/views/attorneys/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Attorneys</h1>

<div id="attorneys">
  <% @attorneys.each do |attorney| %>
    <%= render attorney %>
    <p>
      <%= link_to "Show this attorney", attorney %>
    </p>
  <% end %>
</div>

<%= link_to "New attorney", new_attorney_path %>

app/views/attorneys/new.html.erb
<h1>New attorney</h1>

<%= render "form", attorney: @attorney %>

<br>

<div>
  <%= link_to "Back to attorneys", attorneys_path %>
</div>

app/views/attorneys/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @attorney %>

<div>
  <%= link_to "Edit this attorney", edit_attorney_path(@attorney) %> |
  <%= link_to "Back to attorneys", attorneys_path %>

  <%= button_to "Destroy this attorney", @attorney, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Caseprism</title>
    <link rel="shortcut icon" type="image/x-icon" href="logo.png">
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.css">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
          <p class="notice"><%= notice %></p>
        <% if user_signed_in? %>
          <p class="alert"><%= alert %></p>
        <% end %> 
    <%= yield %>
  </body>
</html>

app/views/pages/hello.html.erb
pages hello

app/views/pages/home.html.erb
<% if user_signed_in? %>

<%= button_to "Log Out", destroy_user_session_path, method: :delete %>

<h3><%= current_user.email %></h3>
	<p> 
		<%= link_to "Home", "#" %>
		<%= link_to "MsWord-Template", msword_path %>
		<%= link_to "Authorization for Relase of Information", "#" %>
	</p>

<% end %>

app/views/pages/msword.html.erb
msword